# Generated by Django 2.2.5 on 2019-09-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190907_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='个人链接'),
        ),
    ]
